// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    Rect: typeof import('./src/components/Rect.vue')['default']
  }
}

export { }
